services:
  postgres:
    container_name: portfolio-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "maindatabase"
      POSTGRES_USER: "kaiofelps"
      POSTGRES_PASSWORD: "kjnsfd76tc937vds"
